### ISSUE TITLE
Ephemeral v2

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2116]
- handle issues way better to reduce logic trigger and function runtime length
- handle error for PUT when 204 returns which is actually success
```
{
  "error": {
    "message": "Expecting JSON, invalid response:\n (http/request@1.1.6/put)",
    "stack": "Error: Expecting JSON, invalid response:\n (http/request@1.1.6/put)\n    at IncomingMessage.<anonymous> (/opt/node_modules/lib/lib/request.js:116:21)\n    at IncomingMessage.emit (events.js:412:35)\n    at endReadableNT (internal/streams/readable.js:1334:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"
  }
}
```
- check when function is triggered, partially resolved
```
{
  "error": {
    "message": "createType(Call):: Call: failed decoding balances.transfer:: Struct: failed on args: {\"dest\":\"MultiAddress\",\"value\":\"Compact<u128>\"}:: Struct: failed on value: Compact<u128>:: Number needs to be an integer <= Number.MAX_SAFE_INTEGER, i.e. 2 ^ 53 - 1",
    "stack": "Error: createType(Call):: Call: failed decoding balances.transfer:: Struct: failed on args: {\"dest\":\"MultiAddress\",\"value\":\"Compact<u128>\"}:: Struct: failed on value: Compact<u128>:: Number needs to be an integer <= Number.MAX_SAFE_INTEGER, i.e. 2 ^ 53 - 1\n    at createTypeUnsafe (/opt/node_modules/@polkadot/types-create/create/type.cjs:73:18)\n    at TypeRegistry.createTypeUnsafe (/opt/node_modules/@polkadot/types/create/registry.cjs:419:46)\n    at extrinsicFn (/opt/node_modules/@polkadot/types/metadata/decorate/extrinsics/createUnchecked.cjs:28:21)\n    at Object.decorated [as transfer] (/opt/node_modules/@polkadot/api/base/Decorate.cjs:462:22)\n    at module.exports (/functions/payout.js:138:4)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
  }
}
```

**Comment by yangwao** [comment]
Create service which would authorize users with their address for their GitHub handle oauth so we don't need for devs fill PR template every PR
