### ISSUE TITLE
Migrate App to Vite

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#2692]
### Is your feature request related to a problem?

I would love to see Vite in the repo. To enable it 

```js
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
  bridge: {
    vite: true,
  }
})
```

[Nuxt Feature Flags](https://v3.nuxtjs.org/getting-started/bridge/#feature-flags)

However, it shows a ton of errors

```
 ERROR  11:33:19 AM [vite] Internal server error: Can't find stylesheet to import.                                                                                                                         11:33:19
  ╷
2 │ @import "~bulma/sass/utilities/_all";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  styles/variables.scss 2:9    @import
  components/Footer.vue 117:9  root stylesheet
  Plugin: vite:css
  File: /Users/vikival/Documents/Work/KodaDot/nft-gallery/styles/variables.scss
  Error: Can't find stylesheet to import.
    ╷
  2 │ @import "~bulma/sass/utilities/_all";
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    styles/variables.scss 2:9    @import
    components/Footer.vue 117:9  root stylesheet
      at Object.wrapException (/Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:1254:17)
      at /Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:69064:25
      at _wrapJsFunctionForAsync_closure.$protected (/Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:3737:15)
      at _wrapJsFunctionForAsync_closure.call$2 (/Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:27919:12)
      at _awaitOnObject_closure.call$1 (/Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:27907:32)
      at Object._rootRunUnary (/Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:4111:18)
      at StaticClosure.<anonymous> (/Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:96990:16)
      at _CustomZone.runUnary$2$2 (/Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:29325:39)
      at _Future__propagateToListeners_handleValueCallback.call$0 (/Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:28388:51)
      at Object._Future__propagateToListeners (/Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:3907:93)
      at _Future._completeWithValue$1 (/Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:28247:9)
      at _AsyncAwaitCompleter.complete$1 (/Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:27894:14)
      at Object._asyncReturn (/Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:3709:17)
      at /Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:69168:24
      at _wrapJsFunctionForAsync_closure.$protected (/Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:3737:15)
      at _wrapJsFunctionForAsync_closure.call$2 (/Users/vikival/Documents/Work/KodaDot/nft-gallery/node_modules/sass/sass.dart.js:27919:12)


```

### Describe the solution you would like

I would like to see Vite 🚀 

### Describe alternatives you have considered

I have tried this Nuxt Bridge with Webpack 4

### Screeenshots

```
ℹ Server built in 11949ms                                                                                                                                                                                  11:38:33
ℹ Waiting for file changes                                                                                                                                                                                 11:38:33
ℹ Memory usage: 636 MB (RSS: 942 MB)                                                                                                                                                                       11:38:33
ℹ Listening on: http://localhost:9090/                                                                                                                                                                     11:38:33
✔ Nitro built in 110 ms                                                                                                                                                                                    11:38:33
```

### Ref
- #2677

**Comment by yangwao** [comment]
Might be related to auto imports?

**Comment by kkukelka** [comment]
Had the same problems when trying to integrate Vite on its own. Vite in its current form cannot handle tilde sign '~' so i think you need to replace it with a regex somewhere in vite config. Let me see if I can find the issue

**Comment by vikiival** [comment]
Wow 💯, nicely written!

**Comment by aito-hideki** [comment]
There's a blocker with Vite migration.
Nuxt i18n (v7 the latest) is not compatible with Vite.
v8 is in development to make it compatible for Vite.

**Comment by yangwao** [comment]
Is this still relevant? Are we using Vite or still Nitro stuff?

**Comment by yangwao** [comment]
Closing in favour 
- https://github.com/kodadot/nft-gallery/issues/3908
