### ISSUE TITLE
Tackle warning after switching to pnpm

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#2694]
Hence introduction pnpm we have a new warning in deploy logs

https://app.netlify.com/sites/koda-nuxt/deploys/62402cd05ae4fc0008a3876d

sounds like need set some pythong env?

```log
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn /usr/bin/python3
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args [
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '/opt/buildhome/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   'binding.gyp',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '-f',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   'make',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '-I',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '/opt/build/repo/node_modules/tiny-secp256k1/build/config.gypi',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '-I',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '/opt/buildhome/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '-I',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '/opt/buildhome/.cache/node-gyp/16.14.2/include/node/common.gypi',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '-Dlibrary=shared_library',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '-Dvisibility=default',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '-Dnode_root_dir=/opt/buildhome/.cache/node-gyp/16.14.2',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '-Dnode_gyp_dir=/opt/buildhome/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '-Dnode_lib_file=/opt/buildhome/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '-Dmodule_root_dir=/opt/build/repo/node_modules/tiny-secp256k1',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '-Dnode_engine=v8',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '--depth=.',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '--no-parallel',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '--generator-output',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   'build',
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args   '-Goutput_dir=.'
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args ]
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn make
11:30:41 AM: node_modules/tiny-secp256k1 install: gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
11:30:41 AM: node_modules/tiny-secp256k1 install: make: Entering directory '/opt/build/repo/node_modules/tiny-secp256k1/build'
11:30:41 AM: node_modules/tiny-secp256k1 install:   CXX(target) Release/obj.target/secp256k1/native/addon.o
11:30:42 AM: node_modules/tiny-secp256k1 install: In file included from ../../nan/nan.h:58,
11:30:42 AM: node_modules/tiny-secp256k1 install:                  from ../native/addon.cpp:4:
11:30:42 AM: node_modules/tiny-secp256k1 install: /opt/buildhome/.cache/node-gyp/16.14.2/include/node/node.h:842:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
```

CF log, seems similar 

```
11:29:46.299	Initializing build environment. This may take up to a few minutes to complete
11:29:48.500	Success: Finished initializing build environment
11:29:48.500	Cloning repository...
11:29:50.737	Success: Finished cloning repository files
11:29:51.123	Installing dependencies
11:29:51.137	Python version set to 2.7
11:29:53.418	Attempting node version '16.14.2' from .node-version
11:29:55.098	Downloading and installing node v16.14.2...
11:29:55.569	Downloading https://nodejs.org/dist/v16.14.2/node-v16.14.2-linux-x64.tar.xz...
11:29:55.962	Computing checksum with sha256sum
11:29:56.095	Checksums matched!
11:30:00.581	Now using node v16.14.2 (npm v8.5.0)
11:30:01.165	Started restoring cached build plugins
11:30:01.182	Finished restoring cached build plugins
11:30:01.926	Attempting ruby version 2.7.1, read from environment
11:30:07.820	Using ruby version 2.7.1
11:30:08.185	Using PHP version 5.6
11:30:08.367	5.2 is already installed.
11:30:08.396	Using Swift version 5.2
11:30:08.397	Started restoring cached node modules
11:30:08.418	Finished restoring cached node modules
11:30:08.901	Installing NPM modules using NPM version 8.5.0
11:30:09.682	8.5.0
11:30:09.689	NPM modules installed
11:30:10.123	Installing Hugo 0.54.0
11:30:10.808	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
11:30:10.813	Started restoring cached go cache
11:30:10.835	Finished restoring cached go cache
11:30:10.996	go version go1.14.4 linux/amd64
11:30:11.017	go version go1.14.4 linux/amd64
11:30:11.021	Installing missing commands
11:30:11.021	Verify run directory
11:30:11.021	Executing user command: npm run generate:pnpm
11:30:11.498	
11:30:11.498	> kodadot-nft-gallery@3.0.0 generate:pnpm
11:30:11.498	> npx pnpm i --store=node_modules/.pnpm-store && npx pnpm generate
11:30:11.498	
11:30:12.143	npm WARN exec The following package was not found and will be installed: pnpm
11:30:13.537	Lockfile is up-to-date, resolution step is skipped
11:30:14.259	Packages: +2933
11:30:14.259	++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
11:30:14.690	Progress: resolved 0, reused 0, downloaded 1, added 0
11:30:14.810	Packages are hard linked from the content-addressable store to the virtual store.
11:30:14.810	  Content-addressable store is at: /opt/buildhome/repo/node_modules/.pnpm-store/v3
11:30:14.810	  Virtual store is at:             node_modules/.pnpm
11:30:15.690	Progress: resolved 0, reused 0, downloaded 36, added 25
11:30:16.691	Progress: resolved 0, reused 0, downloaded 64, added 54
11:30:17.690	Progress: resolved 0, reused 0, downloaded 121, added 107
11:30:18.690	Progress: resolved 0, reused 0, downloaded 173, added 166
11:30:19.690	Progress: resolved 0, reused 0, downloaded 194, added 176
11:30:20.692	Progress: resolved 0, reused 0, downloaded 209, added 234
11:30:21.693	Progress: resolved 0, reused 0, downloaded 264, added 316
11:30:22.694	Progress: resolved 0, reused 0, downloaded 303, added 368
11:30:23.696	Progress: resolved 0, reused 0, downloaded 326, added 380
11:30:24.697	Progress: resolved 0, reused 0, downloaded 383, added 440
11:30:25.703	Progress: resolved 0, reused 0, downloaded 491, added 551
11:30:26.707	Progress: resolved 0, reused 0, downloaded 560, added 652
11:30:27.709	Progress: resolved 0, reused 0, downloaded 678, added 781
11:30:28.710	Progress: resolved 0, reused 0, downloaded 754, added 841
11:30:29.711	Progress: resolved 0, reused 0, downloaded 829, added 959
11:30:30.712	Progress: resolved 0, reused 0, downloaded 938, added 1074
11:30:31.713	Progress: resolved 0, reused 0, downloaded 1027, added 1212
11:30:32.713	Progress: resolved 0, reused 0, downloaded 1145, added 1346
11:30:33.715	Progress: resolved 0, reused 0, downloaded 1282, added 1503
11:30:34.714	Progress: resolved 0, reused 0, downloaded 1352, added 1592
11:30:35.716	Progress: resolved 0, reused 0, downloaded 1471, added 1768
11:30:36.715	Progress: resolved 0, reused 0, downloaded 1578, added 1923
11:30:37.723	Progress: resolved 0, reused 0, downloaded 1738, added 2129
11:30:38.724	Progress: resolved 0, reused 0, downloaded 1867, added 2320
11:30:39.724	Progress: resolved 0, reused 0, downloaded 2000, added 2477
11:30:40.727	Progress: resolved 0, reused 0, downloaded 2160, added 2650
11:30:41.732	Progress: resolved 0, reused 0, downloaded 2226, added 2765
11:30:42.727	Progress: resolved 0, reused 0, downloaded 2312, added 2929
11:30:43.741	Progress: resolved 0, reused 0, downloaded 2315, added 2933
11:30:43.976	.../fontawesome-common-types postinstall$ node attribution.js
11:30:44.045	node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
11:30:44.046	node_modules/core-js-pure postinstall$ node -e "try{require('./postinstall')}catch(e){}"
11:30:44.119	.../fontawesome-common-types postinstall: Font Awesome Free 0.2.36 by @fontawesome - https://fontawesome.com
11:30:44.120	.../fontawesome-common-types postinstall: License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
11:30:44.125	.../fontawesome-common-types postinstall: Done
11:30:44.136	node_modules/@apollo/protobufjs postinstall$ node scripts/postinstall
11:30:44.177	node_modules/core-js postinstall: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
11:30:44.177	node_modules/core-js postinstall: The project needs your help! Please consider supporting of core-js:
11:30:44.178	node_modules/core-js postinstall: > https://opencollective.com/core-js 
11:30:44.178	node_modules/core-js postinstall: > https://patreon.com/zloirock 
11:30:44.178	node_modules/core-js postinstall: > https://paypal.me/zloirock 
11:30:44.179	node_modules/core-js postinstall: > bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz 
11:30:44.179	node_modules/core-js postinstall: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
11:30:44.180	node_modules/core-js-pure postinstall: Done
11:30:44.183	node_modules/core-js postinstall: Done
11:30:44.184	node_modules/es5-ext postinstall$ node -e "try{require('./_postinstall')}catch(e){}"
11:30:44.234	node_modules/@apollo/protobufjs postinstall: Done
11:30:44.236	node_modules/bufferutil install$ node-gyp-build
11:30:44.286	node_modules/es5-ext postinstall: Done
11:30:44.287	node_modules/vuex-module-decorators postinstall$ node -e "try{require('./postinstall')}catch(e){}"
11:30:44.347	node_modules/utf-8-validate install$ node-gyp-build
11:30:44.390	node_modules/nodemon postinstall$ node bin/postinstall || exit 0
11:30:44.393	node_modules/vuex-module-decorators postinstall: Done
11:30:44.469	node_modules/yarn preinstall$ :; (node ./preinstall.js > /dev/null 2>&1 || true)
11:30:44.561	node_modules/bufferutil install: Done
11:30:44.593	node_modules/yarn preinstall: Done
11:30:44.597	node_modules/nodemon postinstall: Love nodemon? You can now support the project via the open collective:
11:30:44.597	node_modules/nodemon postinstall:  > https://opencollective.com/nodemon/donate
11:30:44.612	node_modules/nodemon postinstall: Done
11:30:44.666	node_modules/utf-8-validate install: Done
11:30:44.677	.../@fortawesome/fontawesome-svg-core postinstall$ node attribution.js
11:30:44.678	.../@fortawesome/free-brands-svg-icons postinstall$ node attribution.js
11:30:44.678	.../@fortawesome/free-solid-svg-icons postinstall$ node attribution.js
11:30:44.678	.../@fortawesome/free-regular-svg-icons postinstall$ node attribution.js
11:30:44.794	Progress: resolved 0, reused 0, downloaded 2315, added 2933, done
11:30:44.796	.../@fortawesome/fontawesome-svg-core postinstall: Font Awesome Free 1.2.36 by @fontawesome - https://fontawesome.com
11:30:44.797	.../@fortawesome/fontawesome-svg-core postinstall: License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
11:30:44.799	.../@fortawesome/free-brands-svg-icons postinstall: Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
11:30:44.800	.../@fortawesome/free-brands-svg-icons postinstall: License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
11:30:44.800	.../@fortawesome/fontawesome-svg-core postinstall: Done
11:30:44.807	.../@fortawesome/free-brands-svg-icons postinstall: Done
11:30:44.809	node_modules/esbuild postinstall$ node install.js
11:30:44.847	.../@fortawesome/free-solid-svg-icons postinstall: Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
11:30:44.848	.../@fortawesome/free-solid-svg-icons postinstall: License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
11:30:44.850	.../@fortawesome/free-solid-svg-icons postinstall: Done
11:30:44.856	.../@fortawesome/free-regular-svg-icons postinstall: Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
11:30:44.856	.../@fortawesome/free-regular-svg-icons postinstall: License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
11:30:44.860	.../@fortawesome/free-regular-svg-icons postinstall: Done
11:30:44.945	node_modules/esbuild postinstall: Done
11:30:44.967	node_modules/tiny-secp256k1 install$ npm run build || echo "secp256k1 bindings compilation fail. Pure JS implementation will be used."
11:30:45.016	node_modules/usb-detection install$ prebuild-install || node-gyp rebuild
11:30:45.017	node_modules/cypress postinstall$ node index.js --exec install
11:30:45.104	node_modules/node-hid install$ prebuild-install --runtime napi || node-gyp rebuild
11:30:45.654	node_modules/tiny-secp256k1 install: > tiny-secp256k1@1.1.6 build
11:30:45.654	node_modules/tiny-secp256k1 install: > node-gyp rebuild
11:30:45.681	node_modules/node-hid install: Done
11:30:45.815	node_modules/tiny-secp256k1 install: gyp info it worked if it ends with ok
11:30:45.815	node_modules/tiny-secp256k1 install: gyp info using node-gyp@8.4.1
11:30:45.816	node_modules/tiny-secp256k1 install: gyp info using node@16.14.2 | linux | x64
11:30:45.852	node_modules/usb-detection install: Done
11:30:45.974	node_modules/cypress postinstall: Installing Cypress (version: 9.5.2)
11:30:45.977	node_modules/cypress postinstall: [STARTED] Task without title.
11:30:46.047	node_modules/tiny-secp256k1 install: gyp ERR! find Python 
11:30:46.047	node_modules/tiny-secp256k1 install: gyp ERR! find Python Python is not set from command line or npm configuration
11:30:46.047	node_modules/tiny-secp256k1 install: gyp ERR! find Python Python is not set from environment variable PYTHON
11:30:46.047	node_modules/tiny-secp256k1 install: gyp ERR! find Python checking if "python3" can be used
11:30:46.047	node_modules/tiny-secp256k1 install: gyp ERR! find Python - executable path is "/usr/bin/python3"
11:30:46.048	node_modules/tiny-secp256k1 install: gyp ERR! find Python - version is "3.5.2"
11:30:46.048	node_modules/tiny-secp256k1 install: gyp ERR! find Python - version is 3.5.2 - should be >=3.6.0
11:30:46.048	node_modules/tiny-secp256k1 install: gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
11:30:46.048	node_modules/tiny-secp256k1 install: gyp ERR! find Python checking if "python" can be used
11:30:46.048	node_modules/tiny-secp256k1 install: gyp ERR! find Python - executable path is "/opt/buildhome/python2.7/bin/python"
11:30:46.048	node_modules/tiny-secp256k1 install: gyp ERR! find Python - version is "2.7.12"
11:30:46.049	node_modules/tiny-secp256k1 install: gyp ERR! find Python - version is 2.7.12 - should be >=3.6.0
11:30:46.049	node_modules/tiny-secp256k1 install: gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
11:30:46.049	node_modules/tiny-secp256k1 install: gyp ERR! find Python 
11:30:46.049	node_modules/tiny-secp256k1 install: gyp ERR! find Python **********************************************************
11:30:46.049	node_modules/tiny-secp256k1 install: gyp ERR! find Python You need to install the latest version of Python.
11:30:46.049	node_modules/tiny-secp256k1 install: gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
11:30:46.049	node_modules/tiny-secp256k1 install: gyp ERR! find Python you can try one of the following options:
11:30:46.050	node_modules/tiny-secp256k1 install: gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
11:30:46.050	node_modules/tiny-secp256k1 install: gyp ERR! find Python   (accepted by both node-gyp and npm)
11:30:46.050	node_modules/tiny-secp256k1 install: gyp ERR! find Python - Set the environment variable PYTHON
11:30:46.050	node_modules/tiny-secp256k1 install: gyp ERR! find Python - Set the npm configuration variable python:
11:30:46.051	node_modules/tiny-secp256k1 install: gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
11:30:46.051	node_modules/tiny-secp256k1 install: gyp ERR! find Python For more information consult the documentation at:
11:30:46.051	node_modules/tiny-secp256k1 install: gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
11:30:46.051	node_modules/tiny-secp256k1 install: gyp ERR! find Python **********************************************************
11:30:46.051	node_modules/tiny-secp256k1 install: gyp ERR! find Python 
11:30:46.051	node_modules/tiny-secp256k1 install: gyp ERR! configure error 
11:30:46.051	node_modules/tiny-secp256k1 install: gyp ERR! stack Error: Could not find any Python installation to use
11:30:46.051	node_modules/tiny-secp256k1 install: gyp ERR! stack     at PythonFinder.fail (/opt/buildhome/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
11:30:46.052	node_modules/tiny-secp256k1 install: gyp ERR! stack     at PythonFinder.runChecks (/opt/buildhome/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
11:30:46.052	node_modules/tiny-secp256k1 install: gyp ERR! stack     at PythonFinder.<anonymous> (/opt/buildhome/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:266:16)
11:30:46.052	node_modules/tiny-secp256k1 install: gyp ERR! stack     at PythonFinder.execFileCallback (/opt/buildhome/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:297:7)
11:30:46.052	node_modules/tiny-secp256k1 install: gyp ERR! stack     at ChildProcess.exithandler (node:child_process:390:7)
11:30:46.052	node_modules/tiny-secp256k1 install: gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
11:30:46.052	node_modules/tiny-secp256k1 install: gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
11:30:46.052	node_modules/tiny-secp256k1 install: gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
11:30:46.052	node_modules/tiny-secp256k1 install: gyp ERR! System Linux 4.4.0
11:30:46.053	node_modules/tiny-secp256k1 install: gyp ERR! command "/opt/buildhome/.nvm/versions/node/v16.14.2/bin/node" "/opt/buildhome/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
11:30:46.053	node_modules/tiny-secp256k1 install: gyp ERR! cwd /opt/buildhome/repo/node_modules/tiny-secp256k1
11:30:46.053	node_modules/tiny-secp256k1 install: gyp ERR! node -v v16.14.2
11:30:46.053	node_modules/tiny-secp256k1 install: gyp ERR! node-gyp -v v8.4.1
11:30:46.053	node_modules/tiny-secp256k1 install: gyp ERR! not ok 
11:30:46.064	node_modules/tiny-secp256k1 install: secp256k1 bindings compilation fail. Pure JS implementation will be used.
11:30:46.065	node_modules/tiny-secp256k1 install: Done
11:30:48.656	node_modules/cypress postinstall: [SUCCESS] Task without title.
11:30:48.656	node_modules/cypress postinstall: [STARTED] Task without title.
11:31:03.317	node_modules/cypress postinstall: [SUCCESS] Task without title.
11:31:03.317	node_modules/cypress postinstall: [STARTED] Task without title.
11:31:03.344	node_modules/cypress postinstall: [SUCCESS] Task without title.
11:31:04.347	node_modules/cypress postinstall: You can now open Cypress by running: node_modules/.bin/cypress open
11:31:04.348	node_modules/cypress postinstall: https://on.cypress.io/installing-cypress
11:31:04.366	node_modules/cypress postinstall: Done
11:31:04.383	node_modules/nuxt-edge postinstall$ opencollective || exit 0
11:31:04.684	node_modules/nuxt-edge postinstall:                                                              
11:31:04.685	node_modules/nuxt-edge postinstall:                                      :-:                     
11:31:04.685	node_modules/nuxt-edge postinstall:                                    .==-+:                    
11:31:04.685	node_modules/nuxt-edge postinstall:                                   .==. :+- .-=-              
11:31:04.685	node_modules/nuxt-edge postinstall:                                  .==.   :==++-+=.            
11:31:04.686	node_modules/nuxt-edge postinstall:                                 :==.     -**: :+=.           
11:31:04.686	node_modules/nuxt-edge postinstall:                                :+-      :*+++. .++.          
11:31:04.686	node_modules/nuxt-edge postinstall:                               :+-      -*= .++: .=+.         
11:31:04.686	node_modules/nuxt-edge postinstall:                              -+:      =*-   .+*: .=+:        
11:31:04.686	node_modules/nuxt-edge postinstall:                             -+:     .=*-     .=*-  =+:       
11:31:04.686	node_modules/nuxt-edge postinstall:                           .==:     .+*:        -*-  -+-      
11:31:04.686	node_modules/nuxt-edge postinstall:                          .=+:.....:+*-.........:=*=..=*-     
11:31:04.687	node_modules/nuxt-edge postinstall:                          .-=------=++============++====:     
11:31:04.687	node_modules/nuxt-edge postinstall:                                          
11:31:04.687	node_modules/nuxt-edge postinstall:                           Thanks for installing nuxtjs 
11:31:04.687	node_modules/nuxt-edge postinstall:                  Please consider donating to our open collective
11:31:04.687	node_modules/nuxt-edge postinstall:                         to help us maintain this package.
11:31:04.687	node_modules/nuxt-edge postinstall:                                          
11:31:04.687	node_modules/nuxt-edge postinstall:                             Number of contributors: 0
11:31:04.687	node_modules/nuxt-edge postinstall:                               Number of backers: 471
11:31:04.697	node_modules/nuxt-edge postinstall:                               Annual budget: $65,268
11:31:04.698	node_modules/nuxt-edge postinstall:                              Current balance: $9,881
11:31:04.698	node_modules/nuxt-edge postinstall:                                          
11:31:04.698	node_modules/nuxt-edge postinstall:                  Donate: https://opencollective.com/nuxtjs/donate
11:31:04.698	node_modules/nuxt-edge postinstall:                                          
11:31:04.704	node_modules/nuxt-edge postinstall: Done
11:31:05.562	
11:31:05.564	
11:31:05.564	> kodadot-nft-gallery@3.0.0 prepare /opt/buildhome/repo
11:31:05.564	> husky install
11:31:05.564	
11:31:05.727	husky - Git hooks installed
11:31:09.587	
11:31:09.587	> kodadot-nft-gallery@3.0.0 generate /opt/buildhome/repo
11:31:09.587	> nuxi generate
11:31:09.587	
11:31:09.725	Nuxt CLI v3.0.0-27470397.9ebea90
11:33:04.274	Finished
11:33:04.274	Note: No functions dir at /functions found. Skipping.
11:33:04.274	Validating asset output directory
11:33:05.785	Parsed 1 valid header rule.
11:33:04.821	Deploying your site to Cloudflare's global network...
11:33:25.965	Success: Your site was deployed!
```

edit interesting pnpm failed on CF rn now lol without changing anything related to it 

![image](https://user-images.githubusercontent.com/5887929/160276284-394d322c-393d-4f41-b930-e412b305b7bc.png)

**Comment by preschian** [comment]
will check this one
