### ISSUE TITLE
Error on Artists profile on BSX

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#3119]
Error happened between going to artists profile https://deploy-preview-3060--koda-nuxt.netlify.app/bsx/u/bXjmyHufR6HcjAtKNVTV4UjHj3poQW3d2yYWKDdWe5cGGmg3z?page=1
but seems items are being shown 

<img width="550" alt="image" src="https://user-images.githubusercontent.com/5887929/172605984-bdc6af60-93ec-4082-83eb-f77e585f100d.png">

```
{
    "errors": [
        {
            "message": "Cannot query field \"nFTEntities\" on type \"Query\". Did you mean \"nftEntities\" or \"nftEntityById\"?",
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Cannot query field \"nFTEntities\" on type \"Query\". Did you mean \"nftEntities\" or \"nftEntityById\"?",
                        "    at Object.Field (/squid/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:48:31)",
                        "    at Object.enter (/squid/node_modules/graphql/language/visitor.js:323:29)",
                        "    at Object.enter (/squid/node_modules/graphql/utilities/TypeInfo.js:370:25)",
                        "    at visit (/squid/node_modules/graphql/language/visitor.js:243:26)",
                        "    at validate (/squid/node_modules/graphql/validation/validate.js:69:24)",
                        "    at validate (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)",
                        "    at processGraphQLRequest (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)",
                        "    at runMicrotasks (<anonymous>)",
                        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                        "    at async processHTTPRequest (/squid/node_modules/apollo-server-core/dist/runHttpQuery.js:220:30)"
                    ]
                }
            }
        }
    ]
}
```

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/3060#issuecomment-1149795284_

**Comment by vikiival** [comment]
Can't reproduce

**Comment by yangwao** [comment]
> Can't reproduce

you must be logged in. Not logged doesn't happen seems like that
