### ISSUE TITLE
search at rmrk produces magick errors

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3393]
not sure if we're tracking this or if it's a current outage, but search at rmrk produces bunch of errors in console
![image](https://user-images.githubusercontent.com/73316633/178111550-de7a90be-4f3b-4e78-8af7-2a6ed39d42bb.png)
network output: 
```json
{
  "errors": [
    {
      "message": "Variable \"$orderBy\" got invalid value [\"BLOCK_NUMBER_DESC\"]; Enum \"CollectionEntitiesOrderBy\" cannot represent non-string value: [\"BLOCK_NUMBER_DESC\"]. Did you mean the enum value \"BLOCK_NUMBER_DESC\" or \"BLOCK_NUMBER_ASC\"?",
      "extensions": {
        "code": "BAD_USER_INPUT",
        "exception": {
          "stacktrace": [
            "GraphQLError: Variable \"$orderBy\" got invalid value [\"BLOCK_NUMBER_DESC\"]; Enum \"CollectionEntitiesOrderBy\" cannot represent non-string value: [\"BLOCK_NUMBER_DESC\"]. Did you mean the enum value \"BLOCK_NUMBER_DESC\" or \"BLOCK_NUMBER_ASC\"?",
            "    at /usr/local/lib/node_modules/@subql/query/node_modules/graphql/execution/values.js:116:15",
            "    at coerceInputValueImpl (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/utilities/coerceInputValue.js:131:9)",
            "    at coerceInputValue (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/utilities/coerceInputValue.js:37:10)",
            "    at _loop (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/execution/values.js:109:69)",
            "    at coerceVariableValues (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/execution/values.js:121:16)",
            "    at getVariableValues (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/execution/values.js:50:19)",
            "    at buildExecutionContext (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/execution/execute.js:203:61)",
            "    at executeImpl (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/execution/execute.js:101:20)",
            "    at execute (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/execution/execute.js:60:35)",
            "    at execute (/usr/local/lib/node_modules/@subql/query/node_modules/apollo-server-core/dist/requestPipeline.js:206:48)"
          ]
        }
      }
    }
  ]
}

```

**Comment by Jarsen136** [comment]
related to https://github.com/kodadot/nft-gallery/issues/3321 
and may fixed at https://github.com/kodadot/nft-gallery/pull/3323
