### ISSUE TITLE
Passion Feed for Basilisk

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3403]
Passion Feed toggle for BSX currently results in never ending loader with network error:
```json
{
  "errors": [
    {
      "message": "Variable \"$search\" got invalid value { issuer: { in: [] } } at \"search[0]\"; Field \"issuer\" is not defined by type \"NFTEntityWhereInput\". Did you mean \"issuer_eq\", \"issuer_gt\", \"issuer_in\", or \"issuer_lt\"?",
      "extensions": {
        "code": "BAD_USER_INPUT",
        "exception": {
          "stacktrace": [
            "GraphQLError: Variable \"$search\" got invalid value { issuer: { in: [] } } at \"search[0]\"; Field \"issuer\" is not defined by type \"NFTEntityWhereInput\". Did you mean \"issuer_eq\", \"issuer_gt\", \"issuer_in\", or \"issuer_lt\"?",
            "    at /squid/node_modules/graphql/execution/values.js:116:15",
            "    at coerceInputValueImpl (/squid/node_modules/graphql/utilities/coerceInputValue.js:114:9)",
            "    at coerceInputValueImpl (/squid/node_modules/graphql/utilities/coerceInputValue.js:54:14)",
            "    at /squid/node_modules/graphql/utilities/coerceInputValue.js:70:14",
            "    at Array.map (<anonymous>)",
            "    at safeArrayFrom (/squid/node_modules/graphql/jsutils/safeArrayFrom.js:36:23)",
            "    at coerceInputValueImpl (/squid/node_modules/graphql/utilities/coerceInputValue.js:68:50)",
            "    at coerceInputValue (/squid/node_modules/graphql/utilities/coerceInputValue.js:37:10)",
            "    at _loop (/squid/node_modules/graphql/execution/values.js:109:69)",
            "    at coerceVariableValues (/squid/node_modules/graphql/execution/values.js:121:16)"
          ]
        }
      }
    }
  ]
}

```

- [ ] add passion feed resolver (mind the changes implemented after initial PR in rubick)
- https://github.com/kodadot/snek/issues/37
- [ ] implement passion feed on front end

**Comment by yangwao** [comment]
Can we disable it for bsx for now?

**Comment by petersopko** [comment]
> Can we disable it for bsx for now?

- https://github.com/kodadot/nft-gallery/pull/3406

**Comment by prachi00** [comment]
@petersopko we can close this issue right?
