### ISSUE TITLE
Search for NFTs in specific collection

### ISSUE THREAD

**Issue by petersopko** [kodadot/nft-gallery#3434]
currently we have 4 options when it comes to search on top of collection:
![image](https://user-images.githubusercontent.com/73316633/178766995-47f8399f-8ad9-4f7f-b395-c86dd26c5dc3.png)

- [x] search bar input (hotfixed implemented thanks to @roiLeo)
- https://github.com/kodadot/nft-gallery/pull/3432
- [x] buy now toggle works properly for me (showing only NFTs with price)
- [ ] sorting doesn't seem to do anything
- [ ] own toggle indicating to show which NFTs are mine (wallet logged in) seems to be same issue as in 
- https://github.com/kodadot/nft-gallery/issues/3433
```json
{
  "errors": [
    {
      "message": "Variable \"$search\" got invalid value { currentOwner: { equalTo: \"bXkVgiXLvvJAmUNni8huN9NZdjaxKGav9fSszhRXFeg6Xuvih\" } } at \"search[0]\"; Field \"currentOwner\" is not defined by type \"NFTEntityWhereInput\". Did you mean \"currentOwner_eq\", \"currentOwner_gt\", \"currentOwner_in\", \"currentOwner_lt\", or \"currentOwner_gte\"?",
      "extensions": {
        "code": "BAD_USER_INPUT",
        "exception": {
          "stacktrace": [
            "GraphQLError: Variable \"$search\" got invalid value { currentOwner: { equalTo: \"bXkVgiXLvvJAmUNni8huN9NZdjaxKGav9fSszhRXFeg6Xuvih\" } } at \"search[0]\"; Field \"currentOwner\" is not defined by type \"NFTEntityWhereInput\". Did you mean \"currentOwner_eq\", \"currentOwner_gt\", \"currentOwner_in\", \"currentOwner_lt\", or \"currentOwner_gte\"?",
            "    at /squid/node_modules/graphql/execution/values.js:116:15",
            "    at coerceInputValueImpl (/squid/node_modules/graphql/utilities/coerceInputValue.js:114:9)",
            "    at coerceInputValueImpl (/squid/node_modules/graphql/utilities/coerceInputValue.js:54:14)",
            "    at /squid/node_modules/graphql/utilities/coerceInputValue.js:70:14",
            "    at Array.map (<anonymous>)",
            "    at safeArrayFrom (/squid/node_modules/graphql/jsutils/safeArrayFrom.js:36:23)",
            "    at coerceInputValueImpl (/squid/node_modules/graphql/utilities/coerceInputValue.js:68:50)",
            "    at coerceInputValue (/squid/node_modules/graphql/utilities/coerceInputValue.js:37:10)",
            "    at _loop (/squid/node_modules/graphql/execution/values.js:109:69)",
            "    at coerceVariableValues (/squid/node_modules/graphql/execution/values.js:121:16)"
          ]
        }
      }
    }
  ]
}

```

**Comment by roiLeo** [comment]
btw I didn't fix searchSuggest yet

**Comment by petersopko** [comment]
> btw I didn't fix searchSuggest yet

at the level of specific collections, we don't have search suggest at RMRK either, when it comes to collections/gallery, we're tracking it here
- https://github.com/kodadot/nft-gallery/issues/3433
