### ISSUE TITLE
GraphQL error: value "99999999000000000000" is out of range for type bigint

### ISSUE THREAD

**Issue by yangwao** [kodadot/nft-gallery#4894]
on rmrk

Noticed on 
- #4863 deploy preview

![image](https://user-images.githubusercontent.com/5887929/216279217-a4785b6e-79ba-40f9-ada3-792045ee3a4e.png)

![image](https://user-images.githubusercontent.com/5887929/216279183-9f03fdb3-ae5d-4c6e-a81f-bd72e690c110.png)

**Comment by JustLuuuu** [comment]
I have the same notification also on bsx.

**Comment by roiLeo** [comment]
Comes from `lastNftListByEvent` query

```gql
query lastNftListByEvent($limit: Float!, $event: String!) {
  events: lastEvent(limit: $limit, offset: 0, interaction: $event) {
    meta: value
    timestamp
    nftId: id
    name
    issuer
    currentOwner
    metadata
    animationUrl
    image
    collection: name
  }
}
```

```json
{
  "limit": 10,
  "event": "LIST"
}
```
on [rubick 008](https://squid.subsquid.io/rubick/v/008/graphql), more of a backend issue

**Comment by vikiival** [comment]
I am gonna remove decimals from prices 😌 please make sure to update the frontend.

**Comment by yangwao** [comment]
```json
{
    "errors": [
        {
            "message": "value \"99999999000000000000\" is out of range for type bigint",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "events"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "query": "SELECT\n    DISTINCT ne.id as id,\n    ne.name as name,\n    ne.issuer as issuer,\n    ne.metadata as metadata,\n    e.current_owner,\n    me.image as image,\n    me.animation_url,\n    MAX(e.timestamp) as timestamp,\n    MAX(e.meta::bigint) as value,\n    ne.collection_id as collection_id,\n    ce.name as collection_name\n\nFROM event e\n    JOIN nft_entity ne on e.nft_id = ne.id\n    LEFT join metadata_entity me on me.id = ne.metadata\n    LEFT JOIN collection_entity ce on ne.collection_id = ce.id\nWHERE\n    e.interaction = $1\n    AND ne.burned = false\n    \nGROUP BY ne.id, me.id, e.current_owner, me.image, ce.name\nORDER BY MAX(e.timestamp) DESC\nLIMIT $2 OFFSET $3",
                    "parameters": [
                        "LIST",
                        10,
                        0
                    ],
                    "driverError": {
                        "length": 128,
                        "name": "error",
                        "severity": "ERROR",
                        "code": "22003",
                        "where": "parallel worker",
                        "file": "int8.c",
                        "line": "116",
                        "routine": "scanint8"
                    },
                    "length": 128,
                    "severity": "ERROR",
                    "code": "22003",
                    "where": "parallel worker",
                    "file": "int8.c",
                    "line": "116",
                    "routine": "scanint8",
                    "stacktrace": [
                        "QueryFailedError: value \"99999999000000000000\" is out of range for type bigint",
                        "    at PostgresQueryRunner.query (/squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)",
                        "    at runMicrotasks (<anonymous>)",
                        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                        "    at async DataSource.query (/squid/node_modules/typeorm/data-source/DataSource.js:334:20)",
                        "    at async EventResolver.lastEvent (/squid/lib/server-extension/resolvers/event.js:33:24)"
                    ]
                }
            }
        }
    ],
    "data": null
}
```

**Comment by yangwao** [comment]
https://github.com/kodadot/rubick/actions/runs/4107277189

**Comment by vikiival** [comment]
<img width="896" alt="Screenshot 2023-02-06 at 20 51 46" src="https://user-images.githubusercontent.com/22471030/217070928-b774d689-5397-41bb-aa84-20d4178ca4d0.png">

**Comment by yangwao** [comment]
seems solved

**Comment by vikiival** [comment]
https://github.com/kodadot/rubick/commit/0a4ca040c91f107f3f7976f6cd0f6fdbacd0f932
