### ISSUE TITLE
[E2E] Test for creating collection is broken

### ISSUE THREAD

**Issue by vikiival** [kodadot/nft-gallery#5067]
In fix #5037

I disabled create button when name and symbol are empty.
Therefore this test is failing.

It would be good to fix the test. 

```
(Attempt 1 of 4) should trigger create collection button on rmrk
[803](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:805)
  (Attempt 2 of 4) should trigger create collection button on rmrk
[804](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:806)
  (Attempt 3 of 4) should trigger create collection button on rmrk
[805](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:807)
  1) should trigger create collection button on rmrk
[806](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:808)

[807](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:809)
  2 passing (1m)
[808](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:810)
  1 failing
[809](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:811)

[810](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:812)
  1) should trigger create collection button on rmrk:
[811](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:813)
     CypressError: Timed out retrying after 10050ms: `cy.click()` failed because this element is `disabled`:
[812](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:814)

[813](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:815)
`<button type="button" disabled="disabled" class="button is-primary is-outlined is-fullwidth">...</button>`
[814](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:816)

[815](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:817)
Fix this problem, or use `{force: true}` to disable error checking.
[816](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:818)

[817](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:819)
https://on.cypress.io/element-cannot-be-interacted-with
[818](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:820)
      at Object.isNotDisabled (http://localhost:9090/__cypress/runner/cypress_runner.js:151869:66)
[819](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:821)
      at runAllChecks (http://localhost:9090/__cypress/runner/cypress_runner.js:130534:26)
[820](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:822)
      at retryActionability (http://localhost:9090/__cypress/runner/cypress_runner.js:130623:16)
[821](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:823)
      at tryCatcher (http://localhost:9090/__cypress/runner/cypress_runner.js:8914:23)
[822](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:824)
      at Function.Promise.attempt.Promise.try (http://localhost:9090/__cypress/runner/cypress_runner.js:6188:29)
[823](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:825)
      at whenStable (http://localhost:9090/__cypress/runner/cypress_runner.js:146724:65)
[824](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:826)
      at <unknown> (http://localhost:9090/__cypress/runner/cypress_runner.js:146165:14)
[825](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:827)
      at tryCatcher (http://localhost:9090/__cypress/runner/cypress_runner.js:8914:23)
[826](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:828)
      at Promise._settlePromiseFromHandler (http://localhost:9090/__cypress/runner/cypress_runner.js:6849:31)
[827](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:829)
      at Promise._settlePromise (http://localhost:9090/__cypress/runner/cypress_runner.js:6906:18)
[828](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:830)
      at Promise._settlePromise0 (http://localhost:9090/__cypress/runner/cypress_runner.js:6951:10)
[829](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:831)
      at Promise._settlePromises (http://localhost:9090/__cypress/runner/cypress_runner.js:7031:18)
[830](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:832)
      at Promise._fulfill (http://localhost:9090/__cypress/runner/cypress_runner.js:6975:18)
[831](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:833)
      at <unknown> (http://localhost:9090/__cypress/runner/cypress_runner.js:8589:46)
[832](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:834)
  From Your Spec Code:
[833](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:835)
      at Context.eval (webpack:///./cypress/e2e/create-collection.cy.ts:12:69)
[834](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:836)

[835](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:837)

[836](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:838)

[837](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:839)
Error: Process returned exit code 1
[838](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:840)
Launched as "pnpm start:static & pnpm wait-on http://localhost:9090 && MATRIX=2 node tests/cypress/e2e-run-tests.js"
[839](https://github.com/kodadot/nft-gallery/actions/runs/4227161554/jobs/7341351968#step:9:841)
Launched at "/__w/nft-gallery/nft-gallery"
```

**Comment by leo-anderson-x** [comment]
It seems like this issue is no longer valid? Because #5070 has already reverted the change to disable the button.

**Comment by vikiival** [comment]
Thank you for info 😇
