### ISSUE TITLE
Drops page pops up "failed to mint"

### ISSUE THREAD

**Issue by helloitsdamsky** [kodadot/nft-gallery#6313]
### What happened?

Wanted to mint a drop, pop up says "failed to mint" without any further explanation.

Solution: Add reasoning so user can act on it.

### Please reproduce in steps

/

### Expected Behavior

/

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

<img width="544" alt="image" src="https://github.com/kodadot/nft-gallery/assets/92786519/21e683fb-2de9-4226-9562-5507de763878">
<img width="540" alt="image" src="https://github.com/kodadot/nft-gallery/assets/92786519/879ec1cd-3705-45ed-b790-f74ac90c62e5">

### Relevant log output

```shell
Uncaught (in promise) Error: Decoding undefined: Invalid decoded address length
    at jt (faeb4a0.js:1:250082)
    at d (faeb4a0.js:1:794761)
    at c628fb0.js:1:1779868
    at c (widget.js:1:2206)
    at Generator._invoke (widget.js:1:1959)
    at Generator.next (widget.js:1:2569)
    at r (035a9b4.js:1:115397)
    at l (035a9b4.js:1:115600)
    at 035a9b4.js:1:115659
    at new Promise (<anonymous>)
    at 035a9b4.js:1:115540
    at U (c628fb0.js:1:1780644)
    at F (c628fb0.js:1:1779527)
    at c628fb0.js:1:1780957
    at Array.forEach (<anonymous>)
    at c628fb0.js:1:1780936
    at c (widget.js:1:2206)
    at Generator._invoke (widget.js:1:1959)
    at Generator.next (widget.js:1:2569)
    at r (035a9b4.js:1:115397)
    at l (035a9b4.js:1:115600)
4faeb4a0.js:1 Uncaught (in promise) Error: Decoding undefined: Invalid decoded address length
    at jt (faeb4a0.js:1:250082)
    at d (faeb4a0.js:1:794761)
    at c628fb0.js:1:1779868
    at c (widget.js:1:2206)
    at Generator._invoke (widget.js:1:1959)
    at Generator.next (widget.js:1:2569)
    at r (035a9b4.js:1:115397)
    at l (035a9b4.js:1:115600)
    at 035a9b4.js:1:115659
    at new Promise (<anonymous>)
    at 035a9b4.js:1:115540
    at F (c628fb0.js:1:1779527)
    at c628fb0.js:1:1780957
    at Array.forEach (<anonymous>)
    at c628fb0.js:1:1780936
    at c (widget.js:1:2206)
    at Generator._invoke (widget.js:1:1959)
    at Generator.next (widget.js:1:2569)
    at r (035a9b4.js:1:115397)
    at l (035a9b4.js:1:115600)
o4503930691256320.ingest.sentry.io/api/4503930702331904/envelope/?sentry_key=6fc80708bf024dc8b43c3058f8260dd6&sentry_version=7&sentry_client=sentry.javascript.vue%2F7.54.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o4503930691256320.ingest.sentry.io/api/4503930702331904/envelope/?sentry_key=6fc80708bf024dc8b43c3058f8260dd6&sentry_version=7&sentry_client=sentry.javascript.vue%2F7.54.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
8eb377a.js:1 2023-06-23 12:24:46        API/INIT: statemine/9420: Not decorating runtime apis without matching versions: FungiblesApi/2 (1 known)
(anonymous) @ 8eb377a.js:1
8eb377a.js:1 error [FETCH BALANCE] Unable to get user balance Error: Decoding undefined: Invalid decoded address length
    at jt (faeb4a0.js:1:250082)
    at faeb4a0.js:1:1881594
    at e._subscribe (faeb4a0.js:1:1873616)
    at e._trySubscribe (faeb4a0.js:1:36653)
    at faeb4a0.js:1:36575
    at C (faeb4a0.js:1:33919)
    at e.subscribe (faeb4a0.js:1:36474)
    at faeb4a0.js:1:52420
    at t.<anonymous> (faeb4a0.js:1:48789)
    at faeb4a0.js:1:36535
    at C (faeb4a0.js:1:33919)
    at e.subscribe (faeb4a0.js:1:36474)
    at faeb4a0.js:1:52682
    at t.<anonymous> (faeb4a0.js:1:48789)
    at faeb4a0.js:1:36535
    at C (faeb4a0.js:1:33919)
    at e.subscribe (faeb4a0.js:1:36474)
    at t.connect (faeb4a0.js:1:56385)
    at e._subscribe (faeb4a0.js:1:1872910)
    at e._trySubscribe (faeb4a0.js:1:36653)
    at faeb4a0.js:1:36575
    at C (faeb4a0.js:1:33919)
    at e.subscribe (faeb4a0.js:1:36474)
    at faeb4a0.js:1:57547
    at t.<anonymous> (faeb4a0.js:1:48789)
    at faeb4a0.js:1:36535
    at C (faeb4a0.js:1:33919)
    at e.subscribe (faeb4a0.js:1:36474)
    at faeb4a0.js:1:51187
    at t.<anonymous> (faeb4a0.js:1:48789)
    at faeb4a0.js:1:36535
    at C (faeb4a0.js:1:33919)
    at e.subscribe (faeb4a0.js:1:36474)
    at e._subscribe (faeb4a0.js:1:1873632)
    at e._trySubscribe (faeb4a0.js:1:36653)
    at faeb4a0.js:1:36575
    at C (faeb4a0.js:1:33919)
    at e.subscribe (faeb4a0.js:1:36474)
    at faeb4a0.js:1:52420
    at t.<anonymous> (faeb4a0.js:1:48789)
    at faeb4a0.js:1:36535
    at C (faeb4a0.js:1:33919)
    at e.subscribe (faeb4a0.js:1:36474)
    at faeb4a0.js:1:52682
    at t.<anonymous> (faeb4a0.js:1:48789)
    at faeb4a0.js:1:36535
    at C (faeb4a0.js:1:33919)
    at e.subscribe (faeb4a0.js:1:36474)
    at t.connect (faeb4a0.js:1:56385)
    at e._subscribe (faeb4a0.js:1:1872910)
(anonymous) @ 8eb377a.js:1
8eb377a.js:1 2023-06-23 12:24:46             VEC: Unable to decode on index 0 createType(Lookup0):: Decoding undefined: Invalid decoded address length
(anonymous) @ 8eb377a.js:1
8eb377a.js:1 2023-06-23 12:24:46        RPC-CORE: subscribeStorage(keys?: Vec<StorageKey>): StorageChangeSet:: createType(Vec<StorageKey>):: createType(Lookup0):: Decoding undefined: Invalid decoded address length
(anonymous) @ 8eb377a.js:1
8eb377a.js:1 2023-06-23 12:24:46             VEC: Unable to decode on index 0 createType(Lookup0):: Decoding undefined: Invalid decoded address length
(anonymous) @ 8eb377a.js:1
8eb377a.js:1 2023-06-23 12:24:46        RPC-CORE: subscribeStorage(keys?: Vec<StorageKey>): StorageChangeSet:: createType(Vec<StorageKey>):: createType(Lookup0):: Decoding undefined: Invalid decoded address length
(anonymous) @ 8eb377a.js:1
o4503930691256320.ingest.sentry.io/api/4503930702331904/envelope/?sentry_key=6fc80708bf024dc8b43c3058f8260dd6&sentry_version=7&sentry_client=sentry.javascript.vue%2F7.54.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
8eb377a.js:1  ws subscription: New changes: {"data":{"collectionEntityById":{"nftCount":110}}}
8eb377a.js:1 refetch
o4503930691256320.ingest.sentry.io/api/4503930702331904/envelope/?sentry_key=6fc80708bf024dc8b43c3058f8260dd6&sentry_version=7&sentry_client=sentry.javascript.vue%2F7.54.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
Is this still happening? 
cc @vikiival

**Comment by vikiival** [comment]
Doubt, we closed many PRs related to login
