### ISSUE TITLE
"token":"BelowMinimum" eror while minting NFT into Collection on Polkadot Asset Hub

### ISSUE THREAD

**Issue by helloitsdamsky** [kodadot/nft-gallery#7185]
### What happened?

I’ve minted a collection, placed down the 10 dot deposit, now i want to mint an NFT into it. I have 6.7 DOT available, however it seems there’s an error showing i don’t have balance?

### Please reproduce in steps

/

### Expected Behavior

/

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

![telegram-cloud-photo-size-4-6037510625946614982-x](https://github.com/kodadot/nft-gallery/assets/92786519/77d58960-0849-4584-8282-8213a9deed9d)

### Relevant log output

```shell
ailed to load resource: net::ERR_FAILED
v8b253dfea2ab4077af8c6f58422dfbfd1689876627854:1     Failed to load resource: net::ERR_FAILED
90ed51b.js:4769 No <meta name="viewport"> detected; <model-viewer> will cap pixel density at 1.
(anonymous) @ 90ed51b.js:4769
90ed51b.js:130 info workbox detected i
squid.subsquid.io/speck/v/v2/graphql:1     Failed to load resource: the server responded with a status of 400 ()
90ed51b.js:130 warn Error: Network error: Response not successful: Received status code 400
    at new g (90ed51b.js:5762:155)
    at 90ed51b.js:5762:22958
    at 90ed51b.js:5762:29357
    at Set.forEach (<anonymous>)
    at 90ed51b.js:5762:29332
    at Map.forEach (<anonymous>)
    at R.broadcastQueries (90ed51b.js:5762:29282)
    at 90ed51b.js:5762:21508 Error while fetching default suggestions
value @ 90ed51b.js:130
/ahp/u/manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
90ed51b.js:9 2023-09-06 12:30:41        API/INIT: statemint/9430: Not decorating runtime apis without matching versions: FungiblesApi/2 (1 known)
ki @ 90ed51b.js:9
90ed51b.js:145 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
90ed51b.js:145 api.isConnected? 💚
90ed51b.js:145 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
90ed51b.js:145 api.isConnected? 💚
90ed51b.js:145 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
90ed51b.js:145 api.isConnected? 💚
90ed51b.js:145 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
90ed51b.js:145 api.isConnected? 💚
4fafdc6.js:5 ReferenceError: i is not defined
    at Object.removeOpenListener (90ed51b.js:13:1138)
    at R.<anonymous> (6e07809.js:29:3914)
    at _n (4fafdc6.js:5:30999)
    at Gn (4fafdc6.js:5:26427)
    at Tl.r.$destroy (4fafdc6.js:5:24332)
    at destroy (4fafdc6.js:5:41926)
    at _r (4fafdc6.js:5:59584)
    at _r (4fafdc6.js:5:59697)
    at R.__patch__ (4fafdc6.js:5:63259)
    at Tl.r.$destroy (4fafdc6.js:5:24535)
Is @ 4fafdc6.js:5
squid.subsquid.io/speck/v/v2/graphql:1     Failed to load resource: the server responded with a status of 400 ()
90ed51b.js:130 warn Error: Network error: Response not successful: Received status code 400
    at new g (90ed51b.js:5762:155)
    at 90ed51b.js:5762:22958
    at 90ed51b.js:5762:29357
    at Set.forEach (<anonymous>)
    at 90ed51b.js:5762:29332
    at Map.forEach (<anonymous>)
    at R.broadcastQueries (90ed51b.js:5762:29282)
    at 90ed51b.js:5762:21508 Error while fetching default suggestions
value @ 90ed51b.js:130
image.w.kodadot.xyz/ipfs/QmTEihGN5jdKy9RUoVDtTxtju81zmtdYgDbuYdBJVaQhrC/Jauhar%20Clam.png:1     Failed to load resource: the server responded with a status of 404 ()
90ed51b.js:130  [KODADOT::IMAGE] unable to load https://image.w.kodadot.xyz/ipfs/QmTEihGN5jdKy9RUoVDtTxtju81zmtdYgDbuYdBJVaQhrC/Jauhar%20Clam.png Event
90ed51b.js:130  [KODADOT::IMAGE] unable to load https://image.w.kodadot.xyz/ipfs/QmTEihGN5jdKy9RUoVDtTxtju81zmtdYgDbuYdBJVaQhrC/Jauhar%20Clam.png Event
90ed51b.js:130  [KODADOT::IMAGE] unable to load https://image.w.kodadot.xyz/ipfs/QmTEihGN5jdKy9RUoVDtTxtju81zmtdYgDbuYdBJVaQhrC/Jauhar%20Clam.png Event
90ed51b.js:130  [KODADOT::IMAGE] unable to load https://image.w.kodadot.xyz/ipfs/QmTEihGN5jdKy9RUoVDtTxtju81zmtdYgDbuYdBJVaQhrC/Jauhar%20Clam.png Event
90ed51b.js:130  [KODADOT::IMAGE] unable to load https://image.w.kodadot.xyz/ipfs/QmTEihGN5jdKy9RUoVDtTxtju81zmtdYgDbuYdBJVaQhrC/Jauhar%20Clam.png Event
90ed51b.js:130  [KODADOT::IMAGE] unable to load https://image.w.kodadot.xyz/ipfs/QmTEihGN5jdKy9RUoVDtTxtju81zmtdYgDbuYdBJVaQhrC/Jauhar%20Clam.png Event
90ed51b.js:130  [KODADOT::IMAGE] unable to load https://image.w.kodadot.xyz/ipfs/QmTEihGN5jdKy9RUoVDtTxtju81zmtdYgDbuYdBJVaQhrC/Jauhar%20Clam.png Event
90ed51b.js:145 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
90ed51b.js:145 api.isConnected? 💚
4fafdc6.js:5 ReferenceError: i is not defined
    at Object.removeOpenListener (90ed51b.js:13:1138)
    at R.<anonymous> (6e07809.js:29:3914)
    at _n (4fafdc6.js:5:30999)
    at Gn (4fafdc6.js:5:26427)
    at Tl.r.$destroy (4fafdc6.js:5:24332)
    at destroy (4fafdc6.js:5:41926)
    at _r (4fafdc6.js:5:59584)
    at _r (4fafdc6.js:5:59697)
    at R.__patch__ (4fafdc6.js:5:63259)
    at Tl.r.$destroy (4fafdc6.js:5:24535)
Is @ 4fafdc6.js:5
90ed51b.js:145 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
90ed51b.js:145 api.isConnected? 💚
90ed51b.js:145 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
90ed51b.js:145 api.isConnected? 💚
90ed51b.js:145 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
90ed51b.js:145 api.isConnected? 💚
squid.subsquid.io/speck/v/v2/graphql:1     Failed to load resource: the server responded with a status of 400 ()
90ed51b.js:130  [KODADOT::IMAGE] unable to load https://image.w.kodadot.xyz/ipfs/QmTEihGN5jdKy9RUoVDtTxtju81zmtdYgDbuYdBJVaQhrC/Jauhar%20Clam.png Event (repeated 4469672 times)
90ed51b.js:130 warn Error: Network error: Response not successful: Received status code 400
    at new g (90ed51b.js:5762:155)
    at 90ed51b.js:5762:22958
    at 90ed51b.js:5762:29357
    at Set.forEach (<anonymous>)
    at 90ed51b.js:5762:29332
    at Map.forEach (<anonymous>)
    at R.broadcastQueries (90ed51b.js:5762:29282)
    at 90ed51b.js:5762:21508 Error while fetching default suggestions
value @ 90ed51b.js:130
90ed51b.js:130 warn NavigationDuplicated: Avoided redundant navigation to current location: "/ahp/create?tab=NFT".
    at qr (https://kodadot.xyz/_nuxt/4fafdc6.js:51:18946)
    at $t (https://kodadot.xyz/_nuxt/4fafdc6.js:51:18525)
    at Fe.confirmTransition (https://kodadot.xyz/_nuxt/4fafdc6.js:51:21754)
    at Fe.transitionTo (https://kodadot.xyz/_nuxt/4fafdc6.js:51:21056)
    at I.replace (https://kodadot.xyz/_nuxt/4fafdc6.js:51:24709)
    at https://kodadot.xyz/_nuxt/4fafdc6.js:51:29550
    at new Promise (<anonymous>)
    at Ee.replace (https://kodadot.xyz/_nuxt/4fafdc6.js:51:29512)
    at be (https://kodadot.xyz/_nuxt/90ed51b.js:118:26783)
    at https://kodadot.xyz/_nuxt/90ed51b.js:145:99300
value @ 90ed51b.js:130
90ed51b.js:145 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
90ed51b.js:145 api.isConnected? 💚
90ed51b.js:145 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
90ed51b.js:145 api.isConnected? 💚
90ed51b.js:145 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
90ed51b.js:145 api.isConnected? 💚
90ed51b.js:145 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
90ed51b.js:145 api.isConnected? 💚
90ed51b.js:130  [NFT::STORAGE] Pin File
90ed51b.js:130  [NFT::STORAGE] Pin Json
90ed51b.js:145 [SUPPORT] ss58Format 0
90ed51b.js:145 [SUPPORT] 💋💋💋 0.07784120394395433 KSM
create:1 Access to fetch at 'https://image.w.kodadot.xyz/ipfs/bafybeigxxsebxnfsdbwpgdauxv2ddhxlv6czw434ykr75qtqbpdruwxquu' from origin 'https://kodadot.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
image.w.kodadot.xyz/ipfs/bafybeigxxsebxnfsdbwpgdauxv2ddhxlv6czw434ykr75qtqbpdruwxquu:1     Failed to load resource: net::ERR_FAILED
create:1 Access to fetch at 'https://image.w.kodadot.xyz/ipfs/bafybeigxxsebxnfsdbwpgdauxv2ddhxlv6czw434ykr75qtqbpdruwxquu' from origin 'https://kodadot.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
image.w.kodadot.xyz/ipfs/bafybeigxxsebxnfsdbwpgdauxv2ddhxlv6czw434ykr75qtqbpdruwxquu:1     Failed to load resource: net::ERR_FAILED
90ed51b.js:130 warn [PREHEAT] https://image.w.kodadot.xyz/ipfs/bafybeigxxsebxnfsdbwpgdauxv2ddhxlv6czw434ykr75qtqbpdruwxquu [GET] "https://image.w.kodadot.xyz/ipfs/bafybeigxxsebxnfsdbwpgdauxv2ddhxlv6czw434ykr75qtqbpdruwxquu": <no response> Failed to fetch
value @ 90ed51b.js:130
90ed51b.js:130  [PINNING] Obtain 200
upload.imagedelivery.net/17a06a6f-338d-4e83-aeba-9cc38e224d8b:1     Failed to load resource: the server responded with a status of 409 ()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikiival** [comment]
@helloitsdamsky can you please share transaction or something?

**Comment by helloitsdamsky** [comment]
> @helloitsdamsky can you please share transaction or something?

All i got

https://polkadot.subscan.io/account/15VmrRmgPhKMfBanjS5ei4dCcVL54GMLCfnVRryynSYzvyys

**Comment by helloitsdamsky** [comment]
<img width="414" alt="image" src="https://github.com/kodadot/nft-gallery/assets/92786519/047b534d-3bbd-419b-b9a1-c3488bad513a">

**Comment by vikiival** [comment]
From what I understood is that 

```
	/// Deposit couldn't happen due to the amount being too low. This is usually because the
	/// account doesn't yet exist and the deposit wouldn't bring it to at least the minimum needed
	/// for existance.
	BelowMinimum,
```

The stuff is the support address has not been initialzed yet and needs minimum deposit to operate

**Comment by vikiival** [comment]
cc @helloitsdamsky can we close?
