### ISSUE TITLE
Seems multi buy is broken

### ISSUE THREAD

**Issue by damskyftw** [kodadot/nft-gallery#8469]
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

Wanted to swep floor of .motherboard

### Please reproduce in steps

/

### Expected Behavior

/

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

None

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Asset Hub

### Screenshots

![telegram-cloud-photo-size-4-6021784006191857368-y](https://github.com/kodadot/nft-gallery/assets/92786519/8de07084-cb06-4049-ac3b-d1f50169141c)

### Relevant log output

```shell
entry.75f150bc.js:31 WebSocket connection to 'wss://rpc.basilisk.cloud/' failed: 
connect @ entry.75f150bc.js:31
entry.75f150bc.js:10 2023-12-07 16:58:34          API-WS: disconnected from wss://rpc.basilisk.cloud: 1006:: Abnormal Closure
apply$2 @ entry.75f150bc.js:10
entry.75f150bc.js:32 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
entry.75f150bc.js:32 api.isConnected? 💚
entry.75f150bc.js:32 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
entry.75f150bc.js:32 api.isConnected? 💚
entry.75f150bc.js:31 WebSocket connection to 'wss://rpc.basilisk.cloud/' failed: 
connect @ entry.75f150bc.js:31
entry.75f150bc.js:10 2023-12-07 16:58:36          API-WS: disconnected from wss://rpc.basilisk.cloud: 1006:: Abnormal Closure
apply$2 @ entry.75f150bc.js:10
entry.75f150bc.js:31 WebSocket connection to 'wss://rpc.basilisk.cloud/' failed: 
connect @ entry.75f150bc.js:31
entry.75f150bc.js:10 2023-12-07 16:58:39          API-WS: disconnected from wss://rpc.basilisk.cloud: 1006:: Abnormal Closure
apply$2 @ entry.75f150bc.js:10
w=540:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
entry.75f150bc.js:32 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
entry.75f150bc.js:32 api.isConnected? 💚
entry.75f150bc.js:32 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
entry.75f150bc.js:32 api.isConnected? 💚
entry.75f150bc.js:32 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
entry.75f150bc.js:32 api.isConnected? 💚
entry.75f150bc.js:32 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
entry.75f150bc.js:32 api.isConnected? 💚
support.b28f3a3b.js:1 [SUPPORT] ss58Format 0
useTransaction.815d8bf7.js:1 Royalty is valid: false, amount: 0, address: 
support.b28f3a3b.js:1 [SUPPORT] ss58Format 0
useTransaction.815d8bf7.js:1 Royalty is valid: false, amount: 0, address: 
support.b28f3a3b.js:1 [SUPPORT] ss58Format 0
useTransaction.815d8bf7.js:1 Royalty is valid: false, amount: 0, address: 
support.b28f3a3b.js:1 [SUPPORT] ss58Format 0
useTransaction.815d8bf7.js:1 Royalty is valid: false, amount: 0, address: 
support.b28f3a3b.js:1 [SUPPORT] ss58Format 0
useTransaction.815d8bf7.js:1 Royalty is valid: false, amount: 0, address: 
entry.75f150bc.js:10 2023-12-07 16:59:20        API/INIT: polkadot/1000001: Not decorating runtime apis without matching versions: BeefyApi/3 (1/2 known), ParachainHost/5 (1/2/3/4 known)
apply$2 @ entry.75f150bc.js:10
entry.75f150bc.js:10 2023-12-07 16:59:20        API/INIT: statemint/1000000: Not decorating runtime apis without matching versions: FungiblesApi/2 (1 known)
apply$2 @ entry.75f150bc.js:10
entry.75f150bc.js:32 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
entry.75f150bc.js:32 api.isConnected? 💚
support.b28f3a3b.js:1 [SUPPORT] ss58Format 0
useTransaction.815d8bf7.js:1 Royalty is valid: false, amount: 0, address: 
support.b28f3a3b.js:1 [SUPPORT] ss58Format 0
useTransaction.815d8bf7.js:1 Royalty is valid: false, amount: 0, address: 
support.b28f3a3b.js:1 [SUPPORT] ss58Format 0
useTransaction.815d8bf7.js:1 Royalty is valid: false, amount: 0, address: 
support.b28f3a3b.js:1 [SUPPORT] ss58Format 0
useTransaction.815d8bf7.js:1 Royalty is valid: false, amount: 0, address: 
support.b28f3a3b.js:1 [SUPPORT] ss58Format 0
useTransaction.815d8bf7.js:1 Royalty is valid: false, amount: 0, address: 
entry.75f150bc.js:32 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
entry.75f150bc.js:32 api.isConnected? 💚
useTransaction.815d8bf7.js:1 [EXEC] dispatchError SubmittableResult
(anonymous) @ useTransaction.815d8bf7.js:1
entry.75f150bc.js:32 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
entry.75f150bc.js:32 api.isConnected? 💚
entry.75f150bc.js:32 [KODADOT::SUBAPI] LOG: Api already connected at wss://polkadot-asset-hub-rpc.polkadot.io
entry.75f150bc.js:32 api.isConnected? 💚
workbox-15125c53.js:1 Uncaught (in promise) non-precached-url: non-precached-url :: [{"url":"/"}]
    at Y.createHandlerBoundToURL (https://kodadot.xyz/workbox-15125c53.js:1:18412)
    at Object.createHandlerBoundToURL (https://kodadot.xyz/workbox-15125c53.js:1:21291)
    at https://kodadot.xyz/sw.js:1:42125
    at https://kodadot.xyz/sw.js:1:565
```

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangwao** [comment]
I was thinking what would happen if someone frontruns you... :D

**Comment by yangwao** [comment]
We should check before clicking buy if all NFTs are still on sale. 
If one of that is not on sale, remove it and proceed with buying. 

Maybe some design required by @exezbcz how it should look like
