### ISSUE TITLE
Drop page doesn't generate new variation

### ISSUE THREAD

**Issue by prury** [kodadot/nft-gallery#9622]
![image](https://github.com/kodadot/nft-gallery/assets/36627808/bacdcf17-5d17-4c87-9caf-eb4d4d869db1)

![image](https://github.com/kodadot/nft-gallery/assets/36627808/6ac13f44-f4ee-4184-940c-12cbb348df9d)

`Failed to load resource: the server responded with a status of 500 ()
p5.min.js:2 Uncaught (in promise) DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at n.value (https://image-beta.w.kodadot.xyz/ipfs/bafybeieoszodcraglcjc4v7neopmaicgwotypejy2vpg2cosjh2xb65aj4/p5.min.js:2:481989)
    at f.default.get (https://image-beta.w.kodadot.xyz/ipfs/bafybeieoszodcraglcjc4v7neopmaicgwotypejy2vpg2cosjh2xb65aj4/p5.min.js:2:654137)
    at init (https://image-beta.w.kodadot.xyz/ipfs/bafybeieoszodcraglcjc4v7neopmaicgwotypejy2vpg2cosjh2xb65aj4/sketch.js:62:7)
    at setup (https://image-beta.w.kodadot.xyz/ipfs/bafybeieoszodcraglcjc4v7neopmaicgwotypejy2vpg2cosjh2xb65aj4/sketch.js:49:3)
    at g._setup (https://image-beta.w.kodadot.xyz/ipfs/bafybeieoszodcraglcjc4v7neopmaicgwotypejy2vpg2cosjh2xb65aj4/p5.min.js:2:462519)
    at g._start (https://image-beta.w.kodadot.xyz/ipfs/bafybeieoszodcraglcjc4v7neopmaicgwotypejy2vpg2cosjh2xb65aj4/p5.min.js:2:461202)
    at new g (https://image-beta.w.kodadot.xyz/ipfs/bafybeieoszodcraglcjc4v7neopmaicgwotypejy2vpg2cosjh2xb65aj4/p5.min.js:2:465557)
    at https://image-beta.w.kodadot.xyz/ipfs/bafybeieoszodcraglcjc4v7neopmaicgwotypejy2vpg2cosjh2xb65aj4/p5.min.js:2:451583
web3.min.js:1 `

**Comment by daiagi** [comment]
that's because reflection does not use kodahash render
i.e. we don't know when it finished loading

![image](https://github.com/kodadot/nft-gallery/assets/22791238/0c4db8e4-5757-4b35-948f-781d7b791610)
